### ISSUE TITLE
Sometimes k8s gives back Null and the client dies

### ISSUE THREAD

**Issue by lallydd** [kubernetes-client/haskell#72]
`mimeError = "Error in $.items[39].status.images[11].names: parsing [] failed, expected Array, but encountered Null",`

```json
cat ~/error.json | jq '.items[39].status.images[11]'
{
  "names": null,
  "sizeBytes": 226150943
}
```

I just finished upgrading from 0.1.0.1 to 0.2.0.0 and I get the same error.  Is there some way to get past it?

**Comment by akshaymankar** [comment]
I am guessing you're trying to get nodes here. It looks like `names` is a required field for the `ContainerImage` object as [documented here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerimage-v1-core), yet K8s decided to send a `null` there. I am suspecting this is because some image on the node doesn't have any names and [golang really likes nulls](https://play.golang.org/p/aZOHv_YShtz). I think it is worth raising this in k/k.

In the meanwhile, maybe we can make the client read nulls as empty lists when parsing lists. This might require some change in the openapi generator. Before that happens I am not really sure how to help you. I hope this at least helps in unwinding some mysteries.

**Comment by lallydd** [comment]
On parse failure, i get the response body back out, parse into a `Value`, change any `names` that are `null` to empty lists, and then try parsing it again.  That seems to work around this.
