### ISSUE TITLE
Update to newer LTS?

### ISSUE THREAD

**Issue by joelmccracken** [kubernetes-client/haskell#73]
I'd like to use this on my project, but I would need to update to a newer LTS. Would that be accepted upstream, assuming all else is well? I have never updated an LTS on a big project so I don't totally know what to do.

**Comment by akshaymankar** [comment]
Hey @joelmccracken, yes it would be accepted if you do it. Since this code is generated, you'll have to do it in the openapi-generator. You can look at https://github.com/OpenAPITools/openapi-generator/pull/4068 for inspiration.
Once the PR to the openapi-generator gets merged, you'll have to change the commit SHA in the [settings file](https://github.com/kubernetes-client/haskell/blob/master/settings) and regenerate the code as documented in the [README](https://github.com/kubernetes-client/haskell#update-client).
Please feel free to reach out here if you face any issues while doing so.

**Comment by joelmccracken** [comment]
thanks!

**Comment by jonschoning** [comment]
ill put in a PR to update https://github.com/kubernetes-client/gen since the newest version of openapi generator no longer depends on a ParseTime instance which will make moving to a newer LTS easier

**Comment by jonschoning** [comment]
updating to newer openapi generator, don't need to update /gen. 
https://github.com/kubernetes-client/haskell/pull/75

**Comment by jonschoning** [comment]
@joelmccracken I realize much time has passed, but with https://github.com/kubernetes-client/haskell/pull/75 I don't think there should be as many blockers to move to a later LTS if needed; please let me know if you still would like to keep this issue open

**Comment by joelmccracken** [comment]
Sure that's probably fine. I ended up working around this, so I don't know if I will be able to use i any time soon. If I have issues in the future i'll reopen or file a new ticket.
