### ISSUE TITLE
Issue with (-&-) optional argument operator and Command optional argument for exec

### ISSUE THREAD

**Issue by polygonhell** [kubernetes-client/haskell#76]
In the Exec entry point

Command has to be supplied multiple times in the query string in order to pass parameters
```
(CoreV1.connectGetNamespacedPodExec (Accept MimeAny) name namespace) -&- 
                (Command "ls") -&- 
                (Command "/") -&- 
                (Stdout True) -&- 
                (Stderr True)
```
should result in a query string of 
`?command=ls&command=/&stdout=true&stderr=true`

but actually results in a query string of
`?command=/&stdout=true&stderr=true`

**Comment by jonschoning** [comment]
It looks like the (-&-) operator currently only allows setting a single value.  
I might change the generator to have it default to adding values instead of replacing values, but will have to think about the the right default is.

In the meantime, you can use the `setQuery` function directly to set a list of parameters with the same name at the same time, and they will all be output in the final querystring.
```
connectGetNamespacedPodExec (Accept MimeAny) (Name "") (Namespace "") 
  `setQuery` (toQuery ("command", Just "ls") ++ toQuery("command", Just "/"))
  -&- (Stdout True)
  -&- (Stderr True) 
```

**Comment by polygonhell** [comment]
Thanks, no real rush on this.
I already had a workaround, in order to deal with the transition to web socket in the exec query I have to add a bunch of headers to the query anyway.
I just noticed this as dealing with that.

**Comment by polygonhell** [comment]
One additional point, that might influence which way you decide to go with a solution this came up again with label selectors.

**Comment by jonschoning** [comment]
ah, good to know.  I think part of what exacerbates this is that in the kubernetes swagger spec it looks like `labelSelector` is typed as a string for many of these operations, so the generator doesn't know that this can accept multiple values

**Comment by polygonhell** [comment]
Yes, the problem is one common way collections are passed in query strings is to just repeat them in query.
Which leaves swagger specs are under defined.
One option if your not comfortable changing (-&-) would be to add a second operator (-&&-) that has the add's rather than replaces.

**Comment by jonschoning** [comment]
@polygonhell  Is the spec actually asking for a CSV list instead of multiple instances of the query parameter here? or do both worK?

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering

that would be compatible with the `string` type in the swagger spec.

Still might change the generator, but I wonder if building the CSV list as a string also works for you.

**Comment by polygonhell** [comment]
I think both work, my test seemed to work with multiple instances.

**Comment by polygonhell** [comment]
My error it looks like if you pass 2 labelSelectors it's just ignoring the second one, the correct syntax is as you state comma separated.

**Comment by jonschoning** [comment]
Please re-open if the problem still persists

**Comment by polygonhell** [comment]
Sorry to clarify the command problem still exists, the labelselector issue does not.

**Comment by jonschoning** [comment]
ok i'll put in an update to the generator

**Comment by jonschoning** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/7805

**Comment by jonschoning** [comment]
/close
resolved with https://github.com/OpenAPITools/openapi-generator/pull/7805
